### ISSUE TITLE
Misspell [medium] in multiple .yaml files and indent issue in few

### ISSUE THREAD

**Issue by tw0byt3** [clarkvoss/Nuclei-Templates#2]
@clarkvoss There is a minor misspell "meduim" in the below files which causes error to load the template. Attaching the file with changes if you do not wish to make the changes at your end. 

Actuator.yaml
Dir-Contents-Disc-logs.yaml - Indent issue on line 25
File-manager-search.yaml
Find-wp-config-backup.yaml
Get-Env.yaml 
IBM-Signup-Exposure.yaml 
Kronos-wsld-exposure.yaml 
Letter-Opener-Exposed.yaml 
ProfileService.yaml 
SAP-Path-Traversal.yaml - Indent issue on line 22 (also the severity issue)
Web-xml-finder.yaml 
adminer.php.yaml 
dashboard-exposed.yaml 
elmah-PartnerPortal.yaml 
killswitch.yaml 
sam-search.yaml 
siteminderagent.yaml
[updated_list.zip](https://github.com/clarkvoss/Nuclei-Templates/files/9423816/updated_list.zip)

**Comment by clarkvoss** [comment]
Thanks for the caught and these have been updated.
